services:
  - type: web
    name: jarmfabs-technologies
    runtime: python
    buildCommand: pip install -r requirements.txt && python setup_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
